git config --local user.name "D. Doffy"
git config --local user.email "cuongnsm@gmail.com"
git config --local author.name "D. Doffy"
git config --local author.email "cuongnsm@gmail.com"
git config --local committer.name "D. Doffy"
git config --local committer.email "cuongnsm@gmail.com"
